# Generated by Django 3.0.4 on 2020-05-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('scanhosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useragent', models.CharField(default='', max_length=100, null=True, verbose_name='用户浏览器agent信息')),
                ('blk_id', models.CharField(default='', max_length=256, verbose_name='唯一设备ID')),
            ],
            options={
                'verbose_name': '用户浏览器信息表',
                'verbose_name_plural': '用户浏览器信息表',
                'db_table': 'browse_info',
            },
        ),
        migrations.RenameField(
            model_name='useripinfo',
            old_name='time',
            new_name='update_time',
        ),
        migrations.RemoveField(
            model_name='useripinfo',
            name='ip',
        ),
        migrations.AddField(
            model_name='useripinfo',
            name='ipv4_address',
            field=models.CharField(default='', max_length=40, null=True, verbose_name='ipv4地址'),
        ),
        migrations.AlterModelTable(
            name='useripinfo',
            table='user_ip_info',
        ),
        migrations.DeleteModel(
            name='BrowseInof',
        ),
        migrations.AddField(
            model_name='browseinfo',
            name='user_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanhosts.UserIPInfo'),
        ),
    ]
