# Generated by Django 3.0.4 on 2020-05-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scanhosts', '0002_auto_20200526_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='browseinfo',
            old_name='useragent',
            new_name='user_agent',
        ),
    ]
