# Generated by Django 3.0.4 on 2020-05-28 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('scanhosts', '0003_auto_20200528_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverinfo',
            options={'verbose_name': '服务器', 'verbose_name_plural': '服务器'},
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='created_type',
            field=models.CharField(choices=[('manual', '手动添加'), ('auto', '自动添加')], default='auto', max_length=32,
                                   verbose_name='添加方式'),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='host_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='主机名'),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='hosted_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='hosted_on_server', to='scanhosts.ServerInfo', verbose_name='宿主机'),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='ipv4_add',
            field=models.CharField(default='', max_length=30, verbose_name='IPv4地址'),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='mac_add',
            field=models.CharField(default='', max_length=200, verbose_name='MAC地址'),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='model_type',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='服务器型号'),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='os_distribution',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='系统发行商'),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='os_release',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='操作系统版本'),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='os_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='操作系统类型'),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='server_type',
            field=models.SmallIntegerField(choices=[(1, '刀片服务器'), (0, 'PC服务器'), (2, '小型机')], default=0,
                                           verbose_name='服务器类型'),
        ),
    ]
